### ISSUE TITLE
Blank line at bottom of document is not removed

### ISSUE THREAD

**Issue by Eldaw** [rintoj/blank-line-organizer#4]
When I issue the command 'Remove blank lines', the last blank line right at the bottom of the document is not removed.

I want to remove all blank lines, including the very last one at the bottom.

Here are my settings:

```
    "blankLine.insertLineAfterBlock": false,
    "blankLine.keepOneEmptyLine": false,
    "blankLine.languageIds": [],
    "blankLine.triggerOnSave": false,
```

**Comment by rintoj** [comment]
@Eldaw, I can't reproduce this either:

```
Line1

Line2

Line3

Line4



Line5

```

Was changed to

```
Line1
Line2
Line3
Line4
Line5
```

**Comment by Eldaw** [comment]
@rintoj, this one is also affected by selection only. Try typing a few lines of text, then have your cursor on a blank line right at the bottom of the document. Select All, then hit Ctrl+; to remove all blank lines. Because VS Code doesn't have anything selected on the final line, that one is left out when Remove Blank Lines executes. But I think it's safe to assume that if the user has done Select All, then Remove Blank Lines, that it's safe to also remove the last blank line in the document if they're using the settings in my first post.

**Comment by Eldaw** [comment]
@rintoj, version 0.1.4 doesn't appear to have fixed this, but instead it has brought back the other bug described in #3

**Comment by rintoj** [comment]
@Eldaw, reverted changes. I will work this later.

**Comment by Eldaw** [comment]
I'll close this one for now, as I think that considering the fact that VS Code doesn't select the final line when doing Select All when there is no content on the last line (as there is not even a line break present at that stage), the current behaviour probably makes sense. At the time of the original report, I believe that the issue also affected issuing the Remove Blank Lines command even when there was no selection, however that is no longer the case.
